SCREEN_WIDTH = 1650
SCREEN_HEIGHT = 850
GRID_SIZE = 20

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
DARK_RED = (100, 0, 0)

SNAKE_SPEED = 15

# UI Styles
TITLE_FONT_SIZE = 60
TEXT_FONT_SIZE = 36
CONTROL_FONT_SIZE = 28

BUTTON_WIDTH = 120
BUTTON_HEIGHT = 50

# Play button
BUTTON_PLAY_COLOR = WHITE
BUTTON_PLAY_HOVER_COLOR = YELLOW
BUTTON_PLAY_TEXT_COLOR = BLACK
BUTTON_PLAY_TEXT_HOVER_COLOR = RED
BUTTON_PLAY_SHADOW_COLOR = BLACK

# Exit button (inverted style)
BUTTON_EXIT_COLOR = DARK_RED
BUTTON_EXIT_HOVER_COLOR = RED
BUTTON_EXIT_TEXT_COLOR = WHITE
BUTTON_EXIT_TEXT_HOVER_COLOR = YELLOW
BUTTON_EXIT_SHADOW_COLOR = BLACK

# Shared shadow
SHADOW_OFFSET = 1.5



# Game Over UI
GAME_OVER_FONT_SIZE = 48
GAME_OVER_BUTTON_WIDTH = 150
GAME_OVER_BUTTON_HEIGHT = 50